### ISSUE TITLE
[EPIC] Blend inferred compose information + user overrides with Kompose logic to better control outcome

### ISSUE THREAD

**Issue by marcinc** [appvia/tako#94]
This item has been extracted from #84

Re-use / blend extracted compose information to make better decisions when generating outcome with ported Kompose logic. 
  - [x] service type
  - [x] workload type
  - [x] restart policy
  - [x] image pull policy
  - [x] image pull secret
  - [x] ~resources~ 
  - [x] ~health check~
  - [x] ~replicas~
  - [x] service account
  - [x] ~update strategy (parallelism)~
  - [x] pod security context
  - [-] container security context (we don't support that for now)
  - [x] service node port
  - [x] service TLS secret
  - [x] service domain name
  - [x] PV storage class
  - [x] PV storage size 

^ stroked line items are supported by kompose, and since we inject those blocks in compose they will be taken care of automatically.
